### ISSUE TITLE
Feature Request:  Support comments in swcrc

### ISSUE THREAD

**Issue by hanseltime** [songkeys/tswc#4]
First of all, thanks a ton for making this!  It solves my biggest problem with swc (since most devs I know are gonna look at vscode and tsconfig first and maybe understand swc).

I was testing out the tool and discovered that it currently throws an error if your .swcrc file is more lax json (like comments).  Since .swcrc without this commant seems to support the tsconfig syntax (comments and trailing commas), I would like to see this library support comments in the same way (using the underlying jsonc-parser that get-tsconfig does as well).

I have a PR submitted here: https://github.com/songkeys/tswc/pull/3

Please let me know if there's any concerns about this feature or if it's out of scope of this library or if the library is no longer maintained and I should publish my own package.  Thanks in advance!

**Comment by songkeys** [comment]
closed via #3
